services:
    backend:
        build:
            context: ./backend
            dockerfile: dockerfile
        env_file: .env
        volumes:
            - dist:/app/dist:ro

    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
        volumes:
            - dist:/app/dist:ro

    nginx:
        image: nginx:1.29.3-alpine-slim
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./backend/ssl:/etc/nginx/ssl:ro
            - dist:/app/dist:ro

    redis:
        image: redis:8.2-alpine

    ollama:
        build:
            context: ./ollama
            dockerfile: dockerfile

volumes:
    dist: