services:
    backend:
        build:
            context: ./backend
            dockerfile: dockerfile
        env_file: .env
        volumes:
            - dist:/app/dist:ro

    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
        volumes:
            - dist:/app/dist:ro

    nginx:
        image: nginx:1.29.3-alpine-slim
        ports:
            - 80:80
        volumes:
            - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
            - dist:/app/dist:ro

    ollama:
        image: alpine/ollama:0.12.9

volumes:
    dist: