services:
    backend:
        build:
            context: ./backend
            dockerfile: dockerfile
        command: daphne backend.asgi:application -e ssl:443:privateKey=ssl/private_key.pem:certKey=ssl/certificate.pem
        env_file: .env
        volumes:
            - dist:/app/dist:ro
            - static:/app/static

    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
        volumes:
            - dist:/app/dist:ro

    postgres:
        image: postgres:18.1-alpine
        env_file: .env
        volumes:
            - postgres:/var/lib/postgresql/data

    redis:
        image: redis:8.2-alpine

    ollama:
        image: chatbot-ollama
        build:
            context: ./backend/ollama
            dockerfile: dockerfile

    nginx:
        image: nginx:1.29.3-alpine-slim
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./backend/ssl:/etc/nginx/ssl:ro
            - dist:/app/dist:ro
            - static:/app/static

volumes:
    dist:
    static:
    postgres: