services:
    backend:
        build:
            context: ./backend
            dockerfile: dockerfile
        env_file: .env
        depends_on:
            - redis
            - ollama
        volumes:
            - dist:/app/dist:ro

    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
        depends_on:
            - backend
        volumes:
            - dist:/app/dist:ro

    nginx:
        image: nginx:1.29.3-alpine-slim
        ports:
            - 80:80
        volumes:
            - ./backend/nginx.conf:/etc/nginx/nginx.conf:ro
            - dist:/app/dist:ro
        depends_on:
            - backend

    redis:
        image: redis:8.2-alpine
        restart: unless-stopped

    ollama:
        image: alpine/ollama:0.12.9

volumes:
    dist: