services:
    backend:
        build:
            context: ./backend
            dockerfile: dockerfile
        command: daphne backend.asgi:application -e ssl:443:privateKey=/run/secrets/private_key:certKey=/run/secrets/certificate
        secrets:
            - certificate
            - private_key
        volumes:
            - dist:/app/dist:ro
            - static:/app/static

    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
        volumes:
            - dist:/app/dist:ro

    postgres:
        image: postgres:18.1-alpine
        volumes:
            - postgres:/var/lib/postgresql/data

    redis:
        image: redis:8.4-alpine

    ollama:
        image: chatbot-ollama
        build:
            context: ./backend/ollama
            dockerfile: dockerfile

    nginx:
        image: nginx:1.29.4-alpine-slim
        volumes:
            - dist:/app/dist:ro
            - static:/app/static
        secrets:
            - certificate
            - private_key

volumes:
    dist:
    static:
    postgres:

secrets:
    certificate:
        file: secrets/certificate.pem
    private_key:
        file: secrets/private_key.pem